### ISSUE TITLE
Everything Javascript E01 Remarks

### ISSUE THREAD

**Issue by aladdin83** [me-io/feedback#1]
First thank you for the great effort you put in organizing the event, and also let me appreciate the initiative to build up a unique community of developers without affiliation to a commercial entity.
please understand that my following remarks are not meant to be rude or detract the success of the event.

- the scope of the talk was very wide, talking about es6 was unnecessary or at least should have a dedicated talk.
- too much information, most of the first talk was listing information available online, instead of just presenting documentation try to live code, explain concepts and infer your understanding or share an experience, the second talk about JS performance was more on point in that matter.
- post a short form to collect data about the audience, expertises, languages, and frameworks they work with. and use the data to curate future events.
- less slides, more demos, slides are boring, consider limiting each talk to 15 or less slides, 
- no one can read code listings on a slide, and we will not be able retain too much information just point to a link and show some small snippets, or even better live code.
- don't do a course, courses available online, share an experience, I liked the parts when you were talking about the tools and workflow it's always interests me, I think you should dedicate a talk about automating using task runners. and share your tool set.

and on the issue of sponsorship, I don't think this module is sustainable, if we are to create a developers community better ask the members to contribute, I don't think people will mind paying for their own food and drink, and I think we can find many venues that are happy to host us if we paid a small fee,I don't think 50 or 100 AED will be an issue for attendees.

I am no expert on meetups nor public talks, I am just sharing my ideas, and again forgive me if it sound negative but I really care about and appreciate your initiative. 

thanks

**Comment by meabed** [comment]
Thank you @aladdin83 for taking time, looking back I agree with the points you mentioned here and we would organize better next meetups.
As for the sponsorship idea I think it’s great idea if we able to contribute, and as well if we able to get companies to sponsor both options are not exclusive.
Thank you again I appreciate your feedback ⭐️
